### PR TITLE
Having issues with running http://localhost:8080

### PR DESCRIPTION
**Pull request by Synergy232**
I'm unable to run Jenkins or start testing because the server ran from the special-topics-labs-quality lab is still running. <ctrl>-c isn't working to stop the server. It's still going to http://localhost:8080/hello.

### CODE REVIEW

**Comment by jschmersal-cscc** [comment]
2 things:
1.  I've noticed that sometimes firefox caches the hello world page.  If you think your server is down you can do a hard refresh in firefox (`<ctrl>-reload` or `<ctrl>-F5`) to be sure your server actually is up.  You can also close and re-open your browser.
2.  If the server is still running, you can run `ps -ef | grep java` and kill the processes that are running (the process id is the first column - `kill -9 <pid>` should kill that java process).  Then do the hard refresh like

**Comment by Synergy232** [comment]
What's it asking for after the >?

[CORP\twarren14@a-yincydjxhrr4 e2e]$ 'kill pid 9

>

**Comment by Synergy232** [comment]
my guess would be the process id

**Comment by jschmersal-cscc** [comment]
Sorry - it's the second column that is the process id.  Here's an example:

```
[CORP\jschmersal1@a-1qu102vu4ll0k labs]$ ps -ef | grep java | grep jenkins
ec2-user 31421 31381 17 21:41 ?        00:00:58 java -Duser.home=/usr/share/jenkins/ref -Djenkins.install.runSetupWizard=false -Djenkins.model.Jenkins.slaveAgentPort=50000 -jar /usr/share/jenkins/jenkins.war
[CORP\jschmersal1@a-1qu102vu4ll0k labs]$ kill -9 31421
```

So the process id is a number.  `-9` is a signal (essentially how aggressively you want to kill it... `-9` is kill with extreme prejudice).

**Comment by Synergy232** [comment]
Gotcha. Still not having any luck killing that sever. Still going to Hello World.

**Comment by jschmersal-cscc** [comment]
Is the terminal you started the server in still running?  If not, you could just kill it.  Worst case restart your workspace...

**Comment by Synergy232** [comment]
It's not. I'm going to restart the workspace.

**Comment by jschmersal-cscc** [comment]
Here's what I get when I try to build it:
```
Cloning the remote Git repository
Cloning repository https://github.com/Synergy232/Special_Topics_Lab_V
 > git init /usr/share/jenkins/ref/jobs/build-pipeline-job/workspace@script # timeout=10
Fetching upstream changes from https://github.com/Synergy232/Special_Topics_Lab_V
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/Synergy232/Special_Topics_Lab_V +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/Synergy232/Special_Topics_Lab_V # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/Synergy232/Special_Topics_Lab_V # timeout=10
Fetching upstream changes from https://github.com/Synergy232/Special_Topics_Lab_V
 > git fetch --tags --progress https://github.com/Synergy232/Special_Topics_Lab_V +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/master^{commit} # timeout=10
 > git rev-parse master^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
```

It's saying it can't find a master branch on your repo, which is indeed true - if you go to https://github.com/Synergy232/Special_Topics_Lab_V there is no master branch.  Note: the `build_pipeline.groovy` has a place where it specifies which branch of the repo to pull when looking for a Jenkinsfile to build.  Fixing that up should help.

**Comment by Synergy232** [comment]
Is there a way to change a branch to master on GitHub? I haven't been able to connect to the workspace for longer than 30 seconds today.

**Comment by jschmersal-cscc** [comment]
It's probably easier to just change `build_pipeline.groovy` to reflect the correct branch instead of master.  You can edit it and commit it directly in GH: https://github.com/Synergy232/Special_Topics_Lab_V/blob/completing_assignments/docker/dsl/build_pipeline.groovy

**Comment by Synergy232** [comment]
I just updated the branch to https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start

**Comment by jschmersal-cscc** [comment]
I think I'm getting a little confused because there are 2 different pull requests - https://github.com/Synergy232/Special_Topics_Lab_V/pull/1 and https://github.com/Synergy232/Special_Topics_Lab_V/pull/2.  However, when I look at either I don't see a change to the build_pipeline.groovy file, and looking at all of the branches in your repo I also don't see any commits of the like.

**Comment by Synergy232** [comment]
Not sure, I made the change to the file you linked above on both branches.

**Comment by Synergy232** [comment]
I'm finally able to connect. Now I'm getting the following after the update to build_pipeline.groovy:

Started by user unknown or anonymous
Checking out git https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start into /usr/share/jenkins/ref/jobs/build-pipeline-job/workspace@script to read Jenkinsfile
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start # timeout=10
Fetching upstream changes from https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:144)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: repository 'https://github.com/Synergy232/Special_Topics_Lab_V/tree/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start/' not found

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:892)
	... 8 more
ERROR: Error fetching remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE

**Comment by Synergy232** [comment]
Literally just realized I put the branch in the wrong part of build_pipeline.groovy. It's building something but now I get an error "pipeline block must be at the top-level, not within another block." I moved the pipeline part of the Jenkinsfile to the top and still get the same error. 

-------------------------------------------------------------------
Started by user unknown or anonymous
Checking out git https://github.com/Synergy232/Special_Topics_Lab_V into /usr/share/jenkins/ref/jobs/build-pipeline-job/workspace@script to read Jenkinsfile
No credentials specified
Cloning the remote Git repository
Cloning repository https://github.com/Synergy232/Special_Topics_Lab_V
 > git init /usr/share/jenkins/ref/jobs/build-pipeline-job/workspace@script # timeout=10
Fetching upstream changes from https://github.com/Synergy232/Special_Topics_Lab_V
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/Synergy232/Special_Topics_Lab_V +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://github.com/Synergy232/Special_Topics_Lab_V # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/Synergy232/Special_Topics_Lab_V # timeout=10
Fetching upstream changes from https://github.com/Synergy232/Special_Topics_Lab_V
 > git fetch --tags --progress https://github.com/Synergy232/Special_Topics_Lab_V +refs/heads/*:refs/remotes/origin/*
 > git rev-parse origin/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start^{commit} # timeout=10
Checking out Revision 485679db3113a1125e1600b6021618305c1410e9 (origin/So_i_can_do_a_pull_request_because_i_messed_up_at_the_start)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 485679db3113a1125e1600b6021618305c1410e9
Commit message: "Update build_pipeline.groovy"
First time build. Skipping changelog.
Running in Durability level: MAX_SURVIVABILITY
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 15: pipeline block must be at the top-level, not within another block. @ line 15, column 3.
     pipeline {
     ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:133)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:126)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE

**Pull request closed without merging**
